language: ruby

cache: bundler

jdk:
  - openjdk8

services:
  - docker
  - mysql
  - postgresql
  - xvfb

sudo: false

env:
  - SUITE="rake test test/unit" DB_TYPE=mysql
  - SUITE="rake test test/unit" DB_TYPE=sqlite3
  - SUITE="rake test test/unit" DB_TYPE=postgres
  - SUITE="rake test test/functional" DB_TYPE=mysql
  - SUITE="rake test test/integration" DB_TYPE=mysql
  - SUITE="rspec spec" DB_TYPE=mysql
  # SUITE="rake teaspoon" RAILS_ENV=test DB_TYPE=mysql
  - SUITE="rake assets:precompile RAILS_ENV=production" DB_TYPE=mysql
  - SUITE="rake db:setup RAILS_ENV=production" DB_TYPE=mysql

before_install:
  # starts up a virtuoso docker repository and sets up the config to use it, for the rdf repository related integration tests
  - sh -c "if [ '$SUITE' = 'rake test test/integration' ]; then sh -e script/virtuoso-docker-for-travis.sh; fi"

before_script:
  - sh -c "if [ '$DB_TYPE' = 'pgsql' ]; then psql -c 'create database travis_ci_test; create database travis_ci_dev; create database travis_ci_prod;' -U postgres; fi"
  - cp test/database.travis.$DB_TYPE.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:schema:load
  - sh -c "if [ '$SUITE' = 'rake assets:precompile RAILS_ENV=production' ]; then RAILS_ENV=production bundle exec rake db:create; fi"
  - sh -c "if [ '$SUITE' = 'rake assets:precompile RAILS_ENV=production' ]; then RAILS_ENV=production bundle exec rake db:schema:load; fi"

script: bundle exec $SUITE

