version: '2'
services:
  db: # Database implementation, in this case MySQL
    image: mysql:5.7
    container_name: seek-mysql
    restart: always
    env_file:
      - docker/db.env
    volumes:
      - seek42-mysql-db:/var/lib/mysql

  seek: # The SEEK application
    #build: .
    image: fairdom/seek:1.7
    container_name: seek
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: production
      SOLR_PORT: 8983
      NO_ENTRYPOINT_WORKERS: 1
      OPENBIS_USERNAME: 'admin'
      OPENBIS_PASSWORD: 'changeit'
    env_file:
      - docker/db.env
    volumes:
      - seek4-filestore:/seek4/filestore
      - seek4-cache:/seek4/tmp/cache
    ports:
      - "80:3000"
    depends_on:
      - db
      - solr
    links:
      - db
      - solr

  seek_workers: # The SEEK delayed job workers
      #build: .
      image: fairdom/seek:1.7
      container_name: seek-workers
      command: docker/start_workers.sh
      restart: always
      environment:
        RAILS_ENV: production
        SOLR_PORT: 8983
      env_file:
        - docker/db.env
      volumes:
        - seek4-filestore:/seek4/filestore
        - seek4-cache:/seek4/tmp/cache
      depends_on:
        - db
        - solr
      links:
        - db
        - solr

  openbis:
      image: openbis/debian-openbis:16.05.2
      container_name: openbis
      restart: always
      volumes:
        - openbis-state:/home/openbis/openbis_state
      ports:
        - "4000:443"

  solr:
    image: fairdom/seek-solr
    container_name: seek-solr
    volumes:
      - seek4-solr-data:/opt/solr/server/solr/seek4/data
    restart: always

volumes:
  seek4-filestore:
    external: true
  seek4-mysql-db:
    external: true
  seek4-solr-data:
    external: true
  openbis-state:
    external: true
  seek4-cache:
    external: true
