#Defines mappings between assay type labels, and those in declared in the ontology, but synchronising assay types during
#an upgrade. The key defines the old label, which will be replaced by the assay type defined by the value label, and its associated URI
# assay_type_title_in_assay_types_table :label_from_ontology
#generic experimental assay: experimental assay
#generic modelling analysis: modelling analysis
cdna microarray: transcriptional profiling
modelling analysis type: modelling analysis
experimental assay type: experimental assay
enzymatic: enzymatic assay