Hepatocyte:
  title: Hepatocyte

Liver sinusoidal endothelial cell:
  title: Liver sinusoidal endothelial cell

Hepatic stellate cell:
  title: Hepatic stellate cell

Kupffer cell:
  title: Kupffer cell

Liver lobule:
  title: Liver lobule

Portal vein:
  title: Portal vein

Intralobular bile duct:
  title: Intralobular bile duct

Sinusoid:
  title: Sinusoid

Hepatic artery:
  title: Hepatic artery

Central vein:
  title: Central vein

Liver cancer cell:
  title: Liver cancer cell

Hepatobiliary carcinoma cell:
  title: Hepatobiliary carcinoma cell

Liver acinus:
  title: Liver acinus

Perisinusoidal space:
  title: Perisinusoidal space

Bile canaliculus:
  title: Bile canaliculus

Liver parenchyma:
  title: Liver parenchyma

Liver:
  title: Liver

