root:
  title: <%= I18n.t('project') + "items" %>
  children: models, data, sops, presentations, publications
  deletable: false

models:
  title: <%= I18n.t('model').pluralize %>
  children: published

published:
  title: "Published"

data:
  title: <%= I18n.t('data_file').pluralize %>

sops:
  title: <%= I18n.t('sop').pluralize %>

presentations:
  title: <%= I18n.t('presentation').pluralize %>

publications:
  title: "Publications"

unsorted_items:
  title: "Unsorted items"
  editable: false
  deletable: false
  incoming: true