ODE:
  title: Ordinary differential equations (ODE)

PDE:
  title: Partial differential equations (PDE)

boolean:
  title: Boolean network

Petri:
  title: Petri net

linear equations:
  title: Linear equations

algebraic equations:
  title: Algebraic equations

bayesian:
  title: Bayesian network

graphical:
  title: Graphical model

stoichiometric:
  title: Stoichiometric model

agent based modelling:
  title: Agent based modelling

metabolic_network:
  title: Metabolic network
