construction_data:
  id: 1
  title: Construction data
  description: Data used for model testing

validation_data:
  id: 2
  title: Validation data
  description: Data used for validating a model

produced_data:
  id: 3
  title: Simulation results
  description: Data resulting from running a model simulation
