# This configuration file is used to generate the list of  filters (facets) for each asset type
# The configuration for each filter are:
#   label:  The name of filter to display in UI
#   value_from: How to generate the value inside the filter, can be done through model's association, attribute or method
#               value can be taken from multiple places, separated by comma
#               e.g. value_from: projects:title => will generate object.projects.collect(&:title)
#   facet_class:  exhibit library provide different ways to browse through filters, like list, hierarchy, numeric-range
#                 if not defined it is list by default
#   tree_from:  if the facet_class is Exhibit.HierarchicalFacet you have to define the source to generate the hierarchy tree
#               tree can be taken from multiple places, separated by comma


#isa
Investigation:
  project:
      label: Project
      value_from: projects:title
  created_at:
      label: Created In
      value_from: created_at:year
  contributor:
      label: Contributor
      value_from: contributor:person:name

Study:
  project:
      label: Project
      value_from: projects:title
  created_at:
      label: Created In
      value_from: created_at:year
  contributor:
      label: Contributor
      value_from: contributor:person:name

Assay:
  organism:
      label: Organism
      value_from: organisms:title
  assay_type:
      label: Assay Type
      value_from: assay_type_label
      facet_class: Exhibit.HierarchicalFacet
      tree_from: Seek::Ontologies::AssayTypeReader,Seek::Ontologies::ModellingAnalysisTypeReader
  technology_type:
      label: Technology Type
      value_from: technology_type_label
      facet_class: Exhibit.HierarchicalFacet
      tree_from: Seek::Ontologies::TechnologyTypeReader
  project:
      label: Project
      value_from: projects:title
  created_at:
      label: Created In
      value_from: created_at:year
  contributor:
      label: Contributor
      value_from: contributor:name
  tag:
      label: Tag
      value_from: tags_as_text_array

#assets
DataFile:
  project:
      label: Project
      value_from: projects:title
  assay_type:
        label: Assay Type
        value_from: assay_type_titles
        facet_class: Exhibit.HierarchicalFacet
        tree_from: Seek::Ontologies::AssayTypeReader,Seek::Ontologies::ModellingAnalysisTypeReader
  technology_type:
        label: Technology Type
        value_from: technology_type_titles
        facet_class: Exhibit.HierarchicalFacet
        tree_from: Seek::Ontologies::TechnologyTypeReader
  created_at:
      label: Created In
      value_from: created_at:year
  contributor:
      label: Contributor
      value_from: contributor:person:name,creators:name
  tag:
      label: Tag
      value_from: tags_as_text_array

Model:
  organism:
      label: Organism
      value_from: organism:title
  model_type:
      label: Model Type
      value_from: model_type:title
  model_format:
      label: Model Format
      value_from: model_format:title
  recommended_environment:
      label: Execution or Visualization Environment
      value_from: recommended_environment:title
  modelling_analysis_type:
      label: Modelling Analysis Type
      value_from: assay_type_titles
      facet_class: Exhibit.HierarchicalFacet
      tree_from: Seek::Ontologies::ModellingAnalysisTypeReader
  project:
      label: Project
      value_from: projects:title
  created_at:
      label: Created In
      value_from: created_at:year
  contributor:
      label: Contributor
      value_from: contributor:person:name,creators:name
  tag:
      label: Tag
      value_from: tags_as_text_array

Sop:
  project:
      label: Project
      value_from: projects:title
  technology_type:
        label: Technology Type
        value_from: technology_type_titles
        facet_class: Exhibit.HierarchicalFacet
        tree_from: Seek::Ontologies::TechnologyTypeReader
  assay_type:
        label: Assay Type
        value_from: assay_type_titles
        facet_class: Exhibit.HierarchicalFacet
        tree_from: Seek::Ontologies::AssayTypeReader,Seek::Ontologies::ModellingAnalysisTypeReader
  created_at:
      label: Created In
      value_from: created_at:year
  contributor:
      label: Contributor
      value_from: contributor:person:name,creators:name
  tag:
      label: Tag
      value_from: tags_as_text_array

Publication:
  project:
      label: Project
      value_from: projects:title
  author:
      label: Author
      value_from: publication_author_names
  published_year:
      label: Published Year
      value_from: published_date:year
  organism:
      label: Organism
      value_from: related_organisms:title
  tag:
      label: Tag
      value_from: tags_as_text_array

Presentation:
  project:
      label: Project
      value_from: projects:title
  created_at:
      label: Created In
      value_from: created_at:year
  contributor:
      label: Contributor
      value_from: contributor:person:name,creators:name
  tag:
      label: Tag
      value_from: tags_as_text_array

#yellow pages
Person:
  project:
      label: Project
      value_from: projects:title
  discipline:
      label: Discipline
      value_from: disciplines:title
  expertise:
      label: Expertise
      value_from: expertise:text
  tool:
      label: Tool
      value_from: tools:text
  role:
      label: Role
      value_from: project_positions:title
  institution:
      label: Institution
      value_from: institutions:title
  location:
      label: Location
      value_from: locations
  name:
      label: Name
      value_from: name
  tag:
      label: Tag
      value_from: tags_as_text_array

Project:
  name:
      label: Name
      value_from: title
  organism:
      label: Organism
      value_from: organisms:title
  institution:
      label: Institution
      value_from: institutions:title
  location:
      label: Location
      value_from: locations

Institution:
  name:
      label: Name
      value_from: title
  project:
      label: Project
      value_from: projects:title
  location:
      label: Location
      value_from: country

Programme:
  name:
      label: Name
      value_from: title

#biosamples
Strain:
  organism:
      label: Organism
      value_from: organism:title
  project:
      label: Project
      value_from: projects:title
  gene:
      label: Modified Gene
      value_from: genotypes:gene:title
  created_at:
      label: Created In
      value_from: created_at:year
  contributor:
      label: Contributor
      value_from: contributor:person:name
  tag:
      label: Tag
      value_from: tags_as_text_array

Event:
  project:
      label: Project
      value_from: projects:title
  start_date:
      label: Event date
      value_from: start_date:year
  country:
      label: Country
      value_from: country