default: &default
  adapter: sqlite3
  pool: 25
  timeout: 5000


production:
  <<: *default
  database: sqlite3-db/production.sqlite3

development:
  <<: *default
  database: sqlite3-db/development.sqlite3

test:
  <<: *default
  database: sqlite3-db/test.sqlite3
